# Conexão com o Banco de Dados PostgreSQL (Neon)
spring.datasource.url=jdbc:postgresql://ep-divine-smoke-ai7t7ra6-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Lc32mtTkORIo
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA e Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Porta da Aplicação
server.port=${PORT:8080}
